# Example Site settings

#google_analytics: UA-NNNNNNNN-N

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
repository: Deprofundis2019/Deprofundis2019.github.io
github_url: https://github.com/Deprofundis2019
url: https://Deprofundis2019.github.io
